kind: pipeline
type: docker
name: build

environment:
  ASDF_DATA_DIR: /drone/src/.asdf
  ASDF_DIR: /root/.asdf
  LUA_DIR: /drone/src/.lua
  LUA_BINDIR: /drone/src/.lua/bin
  LUA_INCDIR: /drone/src/.lua/include
  LUA_LIBDIR: /drone/src/.lua/lib
  ARDUPILOT_PATH: /drone/src/ardupilot

steps:
- name: restore ASDF cache
  image: meltwater/drone-cache
  pull: always
  settings:
    restore: true
    backend: filesystem
    cache_key: '{{ checksum ".tool-versions" }}'
    remote_root: asdf
    mount:
      - .asdf
  volumes:
    - name: cache
      path: /tmp/cache

- name: install ASDF
  image: harton.dev/james/asdf_container:latest
  depends_on:
  - restore ASDF cache
  commands:
  - asdf_install

- name: store ASDF cache
  depends_on:
  - install ASDF
  image: meltwater/drone-cache
  pull: always
  settings:
    rebuild: true
    backend: filesystem
    cache_key: '{{ checksum ".tool-versions" }}'
    remote_root: asdf
    mount:
      - .asdf
  volumes:
    - name: cache
      path: /tmp/cache

- name: restore build cache
  image: meltwater/drone-cache
  pull: always
  settings:
    restore: true
    backend: filesystem
    cache_key: '{{ checksum "ardumatic-dev-1.rockspec" }}-{{ checksum ".tool-versions" }}'
    remote_root: ${DRONE_REPO_OWNER}/${DRONE_REPO_NAME}/build
    mount:
      - .lua
  volumes:
    - name: cache
      path: /tmp/cache

- name: build
  image: harton.dev/james/asdf_container:latest
  pull: "always"
  depends_on:
  - restore build cache
  - store ASDF cache
  commands:
  - export PATH="$ASDF_DATA_DIR/shims:$PATH"
  - mkdir -p .lua/bin
  - mkdir -p .lua/include
  - mkdir -p .lua/lib
  - luarocks build

- name: store build cache
  depends_on:
  - build
  image: meltwater/drone-cache
  pull: always
  settings:
    rebuild: true
    backend: filesystem
    cache_key: '{{ checksum "ardumatic-dev-1.rockspec" }}-{{ checksum ".tool-versions" }}'
    remote_root: ${DRONE_REPO_OWNER}/${DRONE_REPO_NAME}/build
    mount:
      - .lua
  volumes:
    - name: cache
      path: /tmp/cache

- name: luarocks lint
  image: harton.dev/james/asdf_container:latest
  depends_on:
  - store build cache
  commands:
  - export PATH="$ASDF_DATA_DIR/shims:$PATH"
  - luarocks lint ardumatic-dev-1.rockspec

- name: luarocks test
  image: harton.dev/james/asdf_container:latest
  depends_on:
  - store build cache
  commands:
  - export PATH="$ASDF_DATA_DIR/shims:$PATH"
  - luarocks test

volumes:
  - name: cache
    host:
      path: /tmp/drone-cache
