stages:
  - build
  - test

image: docker:stable

services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay
  DOCKER_TLS_CERTDIR: ""
  DEV_CONTAINER: registry.gitlab.com/jimsy/ardumatic:dev-container

build:
  stage: build
  before_script:
    - echo ${CI_BUILD_TOKEN} | docker login -u gitlab-ci-token --password-stdin ${CI_REGISTRY}
  script:
    - docker pull $DEV_CONTAINER
    - docker build --cache-from=$DEV_CONTAINER -t $DEV_CONTAINER -f Dockerfile.dev .
    - docker push $DEV_CONTAINER

test:
  stage: test
  before_script:
    - echo ${CI_BUILD_TOKEN} | docker login -u gitlab-ci-token --password-stdin ${CI_REGISTRY}
    - docker pull $DEV_CONTAINER
  script:
    - docker run --rm $DEV_CONTAINER /bin/bash -c 'luarocks test'
