version: "3"

services:
  dev:
    image: registry.gitlab.com/jimsy/ardumatic:dev-container
    build:
      context: .
      dockerfile: Dockerfile.dev
      cache_from:
        - registry.gitlab.com/jimsy/ardumatic:dev-container
      labels:
        - "org.opencontainers.image.source=https://gitlab.com/jimsy/ardumatic"

