version: "3"

services:
  dev:
    image: registry.harton.dev/james/ardumatic:dev-container
    build:
      context: .
      dockerfile: Dockerfile.dev
      cache_from:
        - registry.harton.dev/james/ardumatic:dev-container
      labels:
        - "org.opencontainers.image.source=https://harton.dev/james/ardumatic"

