version: "3"

services:
  dev:
    image: registry.code.harton.nz/james/ardumatic:dev-container
    build:
      context: .
      dockerfile: Dockerfile.dev
      cache_from:
        - registry.code.harton.nz/james/ardumatic:dev-container
      labels:
        - "org.opencontainers.image.source=https://code.harton.nz/james/ardumatic"

