require "busted.runner"
local Frame = require("frame")
local Vec3 = require("vec3")

describe("Frame.new", function()
  describe("when passed a position and rotation", function()
    local position, rotation
    before_each(function()
      position = Vec3.new(1,2,3)
      rotation = Vec3.new(-3, -2, -1):normalize()
    end)

    it("creates a frame instance", function()
      local frame = Frame.new(rotation, position)
      assert.is.truthy(frame:type_of(Frame))
      assert.are.equal(frame.position, position)
      assert.are.equal(frame.rotation, rotation)
    end)
  end)

  describe("when initialised with no arguments", function()
    it("raises an exception", function()
      assert.has.errors(function()
        Frame.new()
      end)
    end)
  end)

  describe("when initialised with a rotation, but no position", function()
    it("creates a frame instance with zero position", function()
      local rotation = Vec3.new(1,0,0)
      local frame = Frame.new(rotation)
      assert.is.truthy(frame:type_of(Frame))
      assert.are.equal(frame.rotation, rotation)
      assert.are.equal(frame.position, Vec3.zero())
    end)
  end)
end)
