require "busted.runner"
local Angle = require("angle")
local CylindricalJoint = require("joint.cylindrical")
local RotationLimit = require("limit.rotation")
local TranslationLimit = require("limit.translation")
local Object = require("object")

describe("CylindricalJoint.new", function()
  it("creates a new CylindricalJoint instance", function()
    local rotation_limit = RotationLimit.new(Angle.zero(), Angle.zero())
    local translation_limit = TranslationLimit.new(0, 0)
    local joint = CylindricalJoint.new(rotation_limit, translation_limit)
    Object.assert_type(joint, CylindricalJoint)
  end)
end)

describe("CylindricalJoint:dof", function()
  it("is 2", function()
    local rotation_limit = RotationLimit.new(Angle.zero(), Angle.zero())
    local translation_limit = TranslationLimit.new(0, 0)
    local joint = CylindricalJoint.new(rotation_limit, translation_limit)
    assert.are.equal(joint.dof, 2)
  end)
end)
